package ch.unibe.scg.team3.game;

import android.os.AsyncTask;
import ch.unibe.scg.team3.board.AbstractBoardGenerator;
import ch.unibe.scg.team3.board.Board;

/**
 * This AsyncTask is used to perform the generation of the board in the
 * background.
 * 
 * @author adrian
 */
public class BoardGenerationTask extends AsyncTask<AbstractBoardGenerator, Void, Board> {

	private final AbstractBoardGenerator generator;

	public BoardGenerationTask(AbstractBoardGenerator gen) {
		generator = gen;
	}

	/**
	 * Generates the board in the background.
	 * 
	 * @param args
	 *            The parameters are not used in this implementation.
	 * @return The board generated by the given {@link AbstractBoardGenerator}.
	 */
	protected Board doInBackground(AbstractBoardGenerator... args) {
		return generator.getBoard();
	}
}
